dist: focal # 20.04
language: python
addons: # Mejor instalarlo como addon que como servicio
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
python:
  - "3.8"
## Configure Oracle 11g R2 XE from https://github.com/Vincit/travis-oracledb-xe
## You will be able to connect the Oracle database in localhost:1521 with user/pass: travis/travis
## and with SYSDBA role user/pass: sys/travis [[simpler: SYSTEM/travis]]
sudo: required
env:
  - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe ORACLE_SID=XE ORACLE_MAX_GESTOR_CONNECTIONS=20 ORACLE_GESTOR_POOL_TIMEOUT_MS=20000 ORACLE_STMT_TIMEOUT_MS=1500 ORACLE_SERVER=localhost ORACLE_PORT=1521 ORACLE_TABLESPACE=USERS ORACLE_USER=SYSTEM ORACLE_PASS=travis ORACLE_MAX_COLS=20 ORACLE_MAX_ROWS=1000 ORACLE_MAX_TABLES=20 PG_USER=postgres PG_PASS=travis PG_SERVER=localhost PG_PORT=5433 PG_DB=postgres PGVER=12 PGPORT=5433 DJANGO_DEVELOPMENT=true
before_install:
  - ./travis_oracle_instant_client.sh # Downloads and unpack Oracle Instant Client
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp/instantclient_19_8 # Update when new versions of Oracle Instant Client are released
  # - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
# command to install dependencies
install:
  - pip install -r requirements.txt
# Set a non-blank password for 'posgres' user
before_script:
  - psql -c "ALTER USER postgres WITH PASSWORD 'travis';"  # Al provenir de addon no necesita el "-U postgres"
# command to run tests
script:
  - ./pylint.sh
  - ./tests_travis.sh