exclude=['lsql/judge/migrations']

# Assume Python 3.13
target-version = "py313"

[lint.per-file-ignores]
# Ignore `F403` (unable to detect undefined names) in settings.py
"lsql/lsql/settings.py" = ["F403"]
# Ignore `F401` (importe by unused) in apps.py for signals
"lsql/judge/apps.py"    = ["F401"]
