#! /bin/bash

export LD_LIBRARY_PATH=/home/iker/TFG/instantclient_19_6:$LD_LIBRARY_PATH
export ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe 
export ORACLE_SID=XE
export ORACLE_MAX_GESTOR_CONNECTIONS=20
export ORACLE_GESTOR_POOL_TIMEOUT_MS=20000 
export ORACLE_STMT_TIMEOUT_MS=1500
export ORACLE_SERVER=localhost 
export ORACLE_PORT=1521
export ORACLE_SID=xe 
export ORACLE_TABLESPACE=USERS 
export ORACLE_USER=SYSTEM 
export ORACLE_PASS=ElPassword 
export ORACLE_MAX_COLS=20 
export ORACLE_MAX_ROWS=1000 
export ORACLE_MAX_TABLES=20 
export PG_USER=postgres
export PG_PASS=iker
export PG_SERVER=localhost 
export PG_PORT=5432 
export PG_DB=postgres
