"""
Commong Django settings for lsql project, that will be used both in DEVELOPMENT or in DEPLOYMENT


Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from datetime import timedelta

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Fails immediately at startup (in both DEVELOPMENT and DEPLOYMENT) if not defined, instead of
# silently falling back to a fresh random key on every process/worker restart
SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "judge.apps.JudgeConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "axes",  # Locks out repeated failed login attempts, see AUTHENTICATION_BACKENDS below
    # 'dbbackup',  # django-dbbackup
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "judge.middleware.SentryUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # django-axes requires its middleware to be the LAST one in the list, since it turns
    # a flagged request into the actual lockout HTTP response after every other
    # middleware/view has already run
    "axes.middleware.AxesMiddleware",
]

# django-axes must come first so locked-out login attempts are rejected before
# ModelBackend ever runs the (deliberately slow) password hash check. We use our own
# RequestOptionalAxesBackend instead of axes.backends.AxesBackend directly because the
# stock backend raises when authenticate() is called without a request - which is
# exactly what Django's test Client.login() shortcut does everywhere in this test suite.
# See judge/axes_backend.py for the full explanation.
AUTHENTICATION_BACKENDS = [
    "judge.axes_backend.RequestOptionalAxesBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Number of failed login attempts allowed before lockout
AXES_FAILURE_LIMIT = 5

# How long an account/IP combination stays locked out after hitting the failure limit
AXES_COOLOFF_TIME = timedelta(hours=1)

# A successful login clears the failure counter, instead of letting past failed
# attempts linger indefinitely toward a future lockout
AXES_RESET_ON_SUCCESS = True

# Lock out the specific (username, IP) combination rather than the IP alone (the
# library default). Students often share IPs (university labs, NAT), so IP-only
# lockout would let one person's failed attempts lock out every other student behind
# the same address; keying on username as well avoids that collateral damage while
# still stopping a targeted brute-force against one account
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]

ROOT_URLCONF = "lsql.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lsql.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    "default": {  # Takes default values if there are no environment variables
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("PG_DB", "postgres"),
        "USER": os.environ.get("PG_USER", "postgres"),
        "PASSWORD": os.environ.get("PG_PASS", ""),
        "HOST": os.environ.get("PG_SERVER", "localhost"),
        "PORT": os.environ.get("PG_PORT", 9000),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "es"

TIME_ZONE = "Europe/Madrid"

USE_I18N = True

# USE_L10N = True  # Default behavior, will be deprecated in Django 5

USE_TZ = True

LOCALE_PATHS = [os.path.join(BASE_DIR, "locale")]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "allstaticfiles")

# Paths for the default authentication system
LOGIN_URL = "/sql/login/"
LOGIN_REDIRECT_URL = "/sql/"

# Configuration of django-dbbackup
# DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
# DBBACKUP_STORAGE_OPTIONS = {'location': f"{os.environ.get('HOME')}/lsql_backups/"}
# DBBACKUP_CLEANUP_KEEP = 16  # 2 months with 2 backups per week
# DBBACKUP_CLEANUP_KEEP_MEDIA = 16


LANGUAGES = (
    ("en", "English"),
    ("es", "Español"),
)
