# Generated by Django 3.0.7 on 2020-06-17 19:09

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_auto_20200617_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectproblem',
            name='expected_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
