# Generated by Django 3.0.7 on 2020-06-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_auto_20200617_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='veredict_code',
            field=models.CharField(choices=[('AC', 'Aceptado'), ('TLE', 'Tiempo limite excedido'), ('RE', 'Error en ejecución'), ('WA', 'Resultados incorrectos'), ('IE', 'Error interno'), ('VE', 'Error de validación')], default='AC', max_length=3),
        ),
    ]
