# Generated by Django 3.0.7 on 2020-07-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_auto_20200619_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='zipfile',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
