# Generated by Django 3.0.7 on 2020-07-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_problem_zipfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='create_sql',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='insert_sql',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
