# Generated by Django 3.0.7 on 2020-07-17 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0011_auto_20200717_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionproblem',
            name='calls',
            field=models.CharField(default='', max_length=5000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='problem',
            name='text_html',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title_html',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='problem',
            name='zipfile',
            field=models.FileField(blank=True, default=None, null=True, upload_to='problem_zips/'),
        ),
    ]
