# Generated by Django 3.0.7 on 2020-07-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0012_auto_20200717_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='zipfile',
            field=models.FileField(blank=True, default=None, null=True, upload_to='collection_zips/'),
        ),
    ]
