# Generated by Django 3.0.7 on 2020-07-20 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0014_auto_20200720_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='create_sql',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='insert_sql',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='text_html',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='text_md',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='selectproblem',
            name='solution',
            field=models.TextField(blank=True, max_length=5000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
