# Generated by Django 3.0.7 on 2020-07-20 14:22

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0016_auto_20200720_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='zipfile',
            field=models.FileField(blank=True, default=None, null=True, upload_to='problem_zips/'),
        ),
        migrations.AlterField(
            model_name='dmlproblem',
            name='expected_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='dmlproblem',
            name='solution',
            field=models.TextField(blank=True, max_length=5000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='functionproblem',
            name='calls',
            field=models.TextField(blank=True, default='', max_length=5000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='functionproblem',
            name='expected_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='functionproblem',
            name='solution',
            field=models.TextField(blank=True, max_length=5000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='procproblem',
            name='expected_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='procproblem',
            name='proc_call',
            field=models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='procproblem',
            name='solution',
            field=models.TextField(blank=True, max_length=5000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='triggerproblem',
            name='expected_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='triggerproblem',
            name='solution',
            field=models.CharField(blank=True, max_length=5000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='triggerproblem',
            name='tests',
            field=models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
