# Generated by Django 3.0.7 on 2020-07-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0017_auto_20200720_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
