# Generated by Django 3.1 on 2020-08-05 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0018_auto_20200720_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggerproblem',
            name='solution',
            field=models.TextField(blank=True, max_length=5000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
