# Generated by Django 3.1.1 on 2020-09-05 22:10

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0019_auto_20200805_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmlproblem',
            name='expected_result',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='functionproblem',
            name='expected_result',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='problem',
            name='initial_db',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='procproblem',
            name='expected_result',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='selectproblem',
            name='expected_result',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='triggerproblem',
            name='expected_result',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
