# Generated by Django 3.1.5 on 2021-03-20 09:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0020_auto_20200906_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=5000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(blank=True, max_length=5000, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='NumSolvedAchievementDefinition',
            fields=[
                ('achievementdefinition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='judge.achievementdefinition')),
                ('num_problems', models.PositiveIntegerField(default=1)),
            ],
            bases=('judge.achievementdefinition', models.Model),
        ),
        migrations.CreateModel(
            name='PodiumAchievementDefinition',
            fields=[
                ('achievementdefinition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='judge.achievementdefinition')),
                ('num_problems', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveIntegerField(default=3)),
            ],
            bases=('judge.achievementdefinition', models.Model),
        ),
        migrations.CreateModel(
            name='ObtainedAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_date', models.DateTimeField(auto_now_add=True)),
                ('achievement_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.achievementdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NumSolvedCollectionAchievementDefinition',
            fields=[
                ('achievementdefinition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='judge.achievementdefinition')),
                ('num_problems', models.PositiveIntegerField(default=1)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.collection')),
            ],
            bases=('judge.achievementdefinition', models.Model),
        ),
    ]
