# Generated by Django 3.1.5 on 2021-03-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0021_achievementdefinition_numsolvedachievementdefinition_numsolvedcollectionachievementdefinition_obtain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obtainedachievement',
            name='obtained_date',
            field=models.DateTimeField(),
        ),
    ]
