# Generated by Django 3.1.5 on 2021-03-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0022_auto_20210327_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obtainedachievement',
            name='obtained_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
