# Generated by Django 3.1.7 on 2021-03-27 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0024_auto_20210327_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obtainedachievement',
            name='obtained_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
