# Generated by Django 3.2 on 2021-04-08 08:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0026_auto_20210407_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscriminantProblem',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='judge.problem')),
                ('check_order', models.BooleanField(default=False)),
                ('correct_query', models.TextField(blank=True, max_length=5000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('incorrect_query', models.TextField(blank=True, max_length=5000, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            bases=('judge.problem',),
        ),
    ]
