# Generated by Django 3.2 on 2021-04-19 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import judge.types


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0028_discriminantproblem_expected_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumSolvedTypeAchievementDefinition',
            fields=[
                ('achievementdefinition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='judge.achievementdefinition')),
                ('num_problems', models.PositiveIntegerField(default=1)),
                ('type_problem', models.CharField(blank=True, choices=[('SELECT', judge.types.ProblemType['SELECT']), ('DML', judge.types.ProblemType['DML']), ('FUNCTION', judge.types.ProblemType['FUNCTION']), ('PROC', judge.types.ProblemType['PROC']), ('TRIGGER', judge.types.ProblemType['TRIGGER']), ('DISC', judge.types.ProblemType['DISC'])], max_length=5000, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            bases=('judge.achievementdefinition', models.Model),
        ),
    ]
