# Generated by Django 3.2 on 2021-04-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0031_rename_type_problem_numsolvedtypeachievementdefinition_problem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='language',
            field=models.CharField(default='es', max_length=200),
        ),
    ]
