# Generated by Django 3.2 on 2021-05-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0032_problem_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='es', max_length=7),
        ),
    ]
