# Generated by Django 3.2 on 2021-05-01 18:48

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0034_alter_achievementdefinition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementdefinition',
            name='description',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
