# Generated by Django 3.2 on 2021-05-06 19:09

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0035_alter_achievementdefinition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementdefinition',
            name='description',
            field=models.JSONField(blank=True, default={'es': ''}, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='achievementdefinition',
            name='name',
            field=models.JSONField(blank=True, default={'es': ''}, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
