# Generated by Django 3.2 on 2021-05-06 19:15

import django.core.serializers.json
from django.db import migrations, models
import judge.models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0037_alter_achievementdefinition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementdefinition',
            name='description',
            field=models.JSONField(blank=True, default=judge.models.default_json_lang, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='achievementdefinition',
            name='name',
            field=models.JSONField(blank=True, default=judge.models.default_json_lang, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
