# Generated by Django 3.2 on 2021-05-06 19:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0038_auto_20210506_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_md', models.TextField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('name_html', models.CharField(blank=True, default='', max_length=200)),
                ('description_md', models.TextField(blank=True, max_length=5000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description_html', models.CharField(blank=True, default='', max_length=10000)),
                ('num_submit', models.PositiveIntegerField(default=1)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
            ],
        ),
    ]
