# Generated by Django 3.2 on 2021-05-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0039_hint_usedhint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedhint',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
