# Generated by Django 3.2.5 on 2021-09-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0041_auto_20210614_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discriminantproblem',
            options={'verbose_name_plural': 'Problem_Discriminant'},
        ),
        migrations.AlterModelOptions(
            name='dmlproblem',
            options={'verbose_name_plural': 'Problem_DML'},
        ),
        migrations.AlterModelOptions(
            name='functionproblem',
            options={'verbose_name_plural': 'Problem_Function'},
        ),
        migrations.AlterModelOptions(
            name='hint',
            options={'verbose_name_plural': 'Hint_definition'},
        ),
        migrations.AlterModelOptions(
            name='numsolvedachievementdefinition',
            options={'verbose_name_plural': 'AchievementDef_NumSolved'},
        ),
        migrations.AlterModelOptions(
            name='numsolvedcollectionachievementdefinition',
            options={'verbose_name_plural': 'AchievementDef_NumSolvedCollection'},
        ),
        migrations.AlterModelOptions(
            name='numsolvedtypeachievementdefinition',
            options={'verbose_name_plural': 'AchievementDef_NumSolvedType'},
        ),
        migrations.AlterModelOptions(
            name='numsubmissionsproblemsachievementdefinition',
            options={'verbose_name_plural': 'AchievementDef_NumSubmissions'},
        ),
        migrations.AlterModelOptions(
            name='obtainedachievement',
            options={'verbose_name_plural': 'Achievement_Obtained'},
        ),
        migrations.AlterModelOptions(
            name='podiumachievementdefinition',
            options={'verbose_name_plural': 'AchievementDef_Podium'},
        ),
        migrations.AlterModelOptions(
            name='procproblem',
            options={'verbose_name_plural': 'Problem_Procedure'},
        ),
        migrations.AlterModelOptions(
            name='selectproblem',
            options={'verbose_name_plural': 'Problem_Select'},
        ),
        migrations.AlterModelOptions(
            name='triggerproblem',
            options={'verbose_name_plural': 'Problem_Trigger'},
        ),
        migrations.AlterModelOptions(
            name='usedhint',
            options={'verbose_name_plural': 'Hint_Used'},
        ),
        migrations.AddField(
            model_name='collection',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
