# Generated by Django 3.2.8 on 2021-12-08 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0043_alter_obtainedachievement_obtained_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obtainedachievement',
            name='obtained_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
