# Generated by Django 6.0.3 on 2026-03-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0044_alter_obtainedachievement_obtained_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['name_html', '-creation_date']},
        ),
    ]
