# Generated by Django 6.0.7 on 2026-07-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0045_alter_collection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict_message',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
